// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYZRI_a59uNLGbpYy79pSaVHlq6-jypR8',
    appId: '1:1092005505168:web:ae3b710dd049adfa0e1015',
    messagingSenderId: '1092005505168',
    projectId: 'aymen-abdulwahab-store',
    authDomain: 'aymen-abdulwahab-store.firebaseapp.com',
    storageBucket: 'aymen-abdulwahab-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYJCSpYJpVec_I8znhkenzEulLdNArKrk',
    appId: '1:1092005505168:android:d0b71ac5998c2f470e1015',
    messagingSenderId: '1092005505168',
    projectId: 'aymen-abdulwahab-store',
    storageBucket: 'aymen-abdulwahab-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxbs35Hk6LIXeRgFyduClfEo79Uy1_wr8',
    appId: '1:1092005505168:ios:a3ca0c4edd3f39360e1015',
    messagingSenderId: '1092005505168',
    projectId: 'aymen-abdulwahab-store',
    storageBucket: 'aymen-abdulwahab-store.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxbs35Hk6LIXeRgFyduClfEo79Uy1_wr8',
    appId: '1:1092005505168:ios:a3ca0c4edd3f39360e1015',
    messagingSenderId: '1092005505168',
    projectId: 'aymen-abdulwahab-store',
    storageBucket: 'aymen-abdulwahab-store.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYZRI_a59uNLGbpYy79pSaVHlq6-jypR8',
    appId: '1:1092005505168:web:acc7ce2c7b48c3540e1015',
    messagingSenderId: '1092005505168',
    projectId: 'aymen-abdulwahab-store',
    authDomain: 'aymen-abdulwahab-store.firebaseapp.com',
    storageBucket: 'aymen-abdulwahab-store.firebasestorage.app',
  );
}
